### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ArthurBonsu** [arifbsmrstu/My-Doctor#2]
when i change the firebase account to mine everything works fine expect the chat it crushes i don't know if i could get ur database json tree cause if i use urs it works fine

**Comment by jasonboateng** [comment]
pls can i get ur firebase json tree db if i change the account name the Activity.chat jus closes with error

**Comment by jasonboateng** [comment]
or at least teach me how to go about it thanks

**Comment by ArthurBonsu** [comment]
My json file suprisinly just has project keys not total db structure. You
still have to login into my account to see my db structure

**Comment by jasonboateng** [comment]
Ummm ok so how do I get into firebase or better yet share database  or export database from json so I see ur tree

**Comment by jasonboateng** [comment]
so can i get the logins  or export the db structure form  firebase.

**Comment by ArthurBonsu** [comment]
Process: com.themebd.mydoctorfinal, PID: 26691
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.themebd.mydoctorfinal/com.themebd.mydoctorfinal.ChatActivity}: java.lang.NullPointerException: Can't pass null for argument 'pathString' in child()
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5299)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException: Can't pass null for argument 'pathString' in child()
this is the error 
        at com.google.firebase.database.DatabaseReference.child(Unknown Source)
        at com.themebd.mydoctorfinal.ChatActivity.loadMessage(ChatActivity.java:244)
        at com.themebd.mydoctorfinal.ChatActivity.onCreate(ChatActivity.java:109)
        at android.app.Activity.performCreate(Activity.java:5264)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:5299) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641) 
        at dalvik.system.NativeStart.main(Native Method) 




so i created a signup class for the doctor which worked then chanced the categories it crashed when i use urs it works did u create a dumb data so the chat will work 
2. how to let the chat work pls

**Comment by arifbsmrstu** [comment]
I added doctor account manually from firebase.

**Comment by ArthurBonsu** [comment]
OK

**Comment by jasonboateng** [comment]
ok sp can iget ur dp structure in firebase i just want see the tree

**Comment by ArthurBonsu** [comment]
hello ls i really  need this can u export ur firebase db for me so i see
how u did it
its for my final year project pls
  export ur database for me pls i beg u

**Comment by ArthurBonsu** [comment]
at least show me the way u did list it down
  what am i doing wrong pls
​

**Comment by arifbsmrstu** [comment]
I am very sorry for my late response, actually i was too sick and in a tight schedule, But i am giving you my database json data. I hope it will help you.

json url:
https://drive.google.com/file/d/1p4vcWByiyIFzxe2SexXyRC1QLX0InKgb/view?usp=sharing

**Comment by jasonboateng** [comment]
thanks so much hope u good now

**Comment by ArthurBonsu** [comment]
Great
